---
- name: Installer Grafana sur container Proxmox
  hosts: grafana_container
  become: yes
  vars_files:
    - vars.yml
    
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - ldap-utils
          - wget
          - gnupg2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ajouter la clé GPG de Grafana
      shell: |
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /usr/share/keyrings/grafana-archive-keyring.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/grafana-archive-keyring.gpg
      when: ansible_os_family == "Debian"

    - name: Ajouter le dépôt Grafana
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://apt.grafana.com stable main"
        state: present
        filename: grafana
      when: ansible_os_family == "Debian"

    - name: Installer Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Corriger les permissions et la configuration Grafana pour LXC/Docker
      shell: |
        # Créer les répertoires nécessaires avec les bonnes permissions
        mkdir -p /var/lib/grafana
        mkdir -p /var/log/grafana
        mkdir -p /etc/grafana/provisioning
        chown -R grafana:grafana /var/lib/grafana
        chown -R grafana:grafana /var/log/grafana
        chown -R grafana:grafana /etc/grafana
        chmod -R 755 /var/lib/grafana
        chmod -R 755 /var/log/grafana
        chmod -R 755 /etc/grafana

    - name: Modifier le service Grafana pour LXC (désactiver les namespaces)
      shell: |
        mkdir -p /etc/systemd/system/grafana-server.service.d
        cat > /etc/systemd/system/grafana-server.service.d/override.conf << EOF
        [Service]
        PrivateDevices=no
        PrivateTmp=no
        NoNewPrivileges=no
        ProtectSystem=no
        ProtectHome=no
        RestartSec=5
        Restart=always
        EOF
        systemctl daemon-reload

    - name: Exécuter Grafana directement pour voir les erreurs
      shell: |
        /usr/share/grafana/bin/grafana server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid > /dev/null 2>&1 &
      ignore_errors: yes

    - name: Vérifier les logs détaillés de Grafana
      shell: |
        sleep 3
        /usr/share/grafana/bin/grafana server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini 2>&1 | head -20
      register: grafana_output
      ignore_errors: yes

    - name: Modifier le fichier de service Grafana pour ajouter le homepath
      lineinfile:
        path: /lib/systemd/system/grafana-server.service
        regexp: "^ExecStart="
        line: "ExecStart=/usr/share/grafana/bin/grafana server --homepath=/usr/share/grafana --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}"
        backup: yes
      notify: Redémarrer Grafana

    - name: Recharger systemd et redémarrer Grafana
      shell: |
        systemctl daemon-reload
        systemctl restart grafana-server

    - name: Créer le répertoire de configuration
      file:
        path: /etc/grafana
        state: directory
        mode: '0755'

    - name: Copier le fichier custom.ini
      copy:
        src: custom.ini
        dest: /etc/grafana/grafana.ini
        owner: grafana
        group: grafana
        mode: '0640'
      notify: Redémarrer Grafana

    - name: Configurer Grafana avec les variables d'environnement
      lineinfile:
        path: /etc/default/grafana-server
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      loop:
        - { regexp: '^GF_SECURITY_ADMIN_USER=', line: 'GF_SECURITY_ADMIN_USER={{ grafana_admin_user }}' }
        - { regexp: '^GF_SECURITY_ADMIN_PASSWORD=', line: 'GF_SECURITY_ADMIN_PASSWORD={{ grafana_admin_password }}' }
        - { regexp: '^GF_SERVER_HTTP_PORT=', line: 'GF_SERVER_HTTP_PORT={{ grafana_port }}' }
      notify: Redémarrer Grafana

    - name: Configurer les variables d'environnement supplémentaires
      lineinfile:
        path: /etc/default/grafana-server
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop: "{{ grafana_env_vars | dict2items }}"
      notify: Redémarrer Grafana

    - name: Activer et démarrer le service Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Attendre que Grafana soit disponible
      wait_for:
        host: "{{ grafana_ip }}"
        port: "{{ grafana_port }}"
        delay: 5
        timeout: 60

    - name: Afficher l'URL de Grafana
      debug:
        msg: "Grafana est accessible sur http://{{ grafana_ip }}:{{ grafana_port }}"

  handlers:
    - name: Redémarrer Grafana
      systemd:
        name: grafana-server
        state: restarted

    
